//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritecWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class abastecimento
    {
        public long id { get; set; }
        public System.DateTime data { get; set; }
        public double horimetro { get; set; }
        public double quantidade { get; set; }
        public int CategoriaAbastecimento_id { get; set; }
        public Nullable<long> ObservacaoAbastecimento_id { get; set; }
        public string Apontador_CloudId { get; set; }
        public long VeiculoObra_Veiculo_id { get; set; }
        public long VeiculoObra_Obra_id { get; set; }
    
        public virtual categoriaabastecimento categoriaabastecimento { get; set; }
        public virtual observacaoabastecimento observacaoabastecimento { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual veiculoobra veiculoobra { get; set; }
    }
}
