//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritecWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcaoprograma
    {
        public int id { get; set; }
        public int Funcao_id { get; set; }
        public int Programa_id { get; set; }
        public int NivelPermissao_id { get; set; }
    
        public virtual funcao funcao { get; set; }
        public virtual programa programa { get; set; }
        public virtual nivelpermissao nivelpermissao { get; set; }
    }
}
