//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritecWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagempatologia
    {
        public long id { get; set; }
        public long Patologia_id { get; set; }
        public System.DateTime data { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public byte[] imagem { get; set; }
    
        public virtual patologia patologia { get; set; }
    }
}
