//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritecWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemaplicacao
    {
        public long id { get; set; }
        public string nota { get; set; }
        public double estaca { get; set; }
        public System.DateTime horaInicio { get; set; }
        public System.DateTime horaFim { get; set; }
        public double largura { get; set; }
        public double comprimento { get; set; }
        public double espessura { get; set; }
        public double toneladas { get; set; }
        public double temperatura { get; set; }
        public long Motorista_id { get; set; }
        public long Veiculo_id { get; set; }
        public long Fase_id { get; set; }
        public string Apontador_CloudId { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual controleaplicacaomassa controleaplicacaomassa { get; set; }
        public virtual motorista motorista { get; set; }
        public virtual veiculo veiculo { get; set; }
    }
}
