//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritecWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veiculo()
        {
            this.itemaplicacao = new HashSet<itemaplicacao>();
            this.veiculoobra = new HashSet<veiculoobra>();
        }
    
        public long id { get; set; }
        public string descricao { get; set; }
        public string placa { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public int CategoriaVeiculo_id { get; set; }
        public long Proprietario_id { get; set; }
    
        public virtual categoriaveiculo categoriaveiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itemaplicacao> itemaplicacao { get; set; }
        public virtual proprietario proprietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<veiculoobra> veiculoobra { get; set; }
    }
}
