//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritecWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class veiculoobra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public veiculoobra()
        {
            this.abastecimento = new HashSet<abastecimento>();
        }
    
        public long Veiculo_id { get; set; }
        public long Obra_id { get; set; }
        public string UsuarioCadastro_CloudId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abastecimento> abastecimento { get; set; }
        public virtual obra obra { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual veiculo veiculo { get; set; }
    }
}
